### ISSUE TITLE
Error: Resource not accessible by integration

### ISSUE THREAD

**Issue by tobbbles** [mktcode/consecutive-workflow-action#33]
Hi! Thanks for the great action, I'm getting the following strange error:

```
Error: Resource not accessible by integration
```

From the workflow:

```
name: Wicked Sick Cool Workflow TM
on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env: {}

jobs:
  consecutiveness:
    runs-on: ubuntu-latest
    steps:
      - uses: mktcode/consecutive-workflow-action@58263570c6949713f8cb7be48534e189254cbd90
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: [consecutiveness]
    steps:
      - name: Setup | checkout
        uses: actions/checkout@v2
```
